### PR TITLE
[Needs work] Remove special characters from "Locations filters label under the map"

### PR DESCRIPTION
**Pull request by andrebonon**
Currently is not possible to add a filter's label with special characters like &.
This PR needs work but give us an idea of how to fix that.

Does anyone have any idea how to fix that properly?

### CODE REVIEW

**Comment by podarok** [comment]
@sarah-halby to add to our Jira

**Comment by sarah-halby** [comment]
Thanks @podarok - could you please add Shelley and Kylie to the sub-projects as well for visibility?

**Comment by shelleygoetz** [comment]
Added to Jira: https://openy.atlassian.net/browse/MAINTAIN-164

**Comment by podarok** [comment]
Done in https://github.com/open-y-subprojects/openy_map/releases/tag/1.3

**Pull request closed without merging**
